
package Interface;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import java.io.IOException;
import java.util.Comparator;
import java.util.Iterator;
import java.util.Optional;
import java.util.Spliterator;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.BinaryOperator;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.IntFunction;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.ToDoubleFunction;
import java.util.function.ToIntFunction;
import java.util.function.ToLongFunction;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.BaseStream;
import java.util.stream.Collector;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.LongStream;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;


public class Principal extends javax.swing.JFrame {


File file;
Workbook workbook;
    private tb1 JTable;
    private Node document;
    private int assuntotipo;




public Principal() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtlocal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jttitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jbpreencher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jttitulo1 = new javax.swing.JTextField();
        jttitulo2 = new javax.swing.JTextField();
        jttitulo3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtlocal.setBackground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jtlocal);
        jtlocal.setBounds(570, 50, 160, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 40, 130, 40);

        jttitulo.setBackground(new java.awt.Color(102, 255, 204));
        jttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttituloActionPerformed(evt);
            }
        });
        getContentPane().add(jttitulo);
        jttitulo.setBounds(570, 90, 160, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("DATAREQUERIMENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 170, 21);

        tb1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tb1.setForeground(new java.awt.Color(0, 153, 153));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATRICULA", "ASSUNTOTIPO", "DATAREQUERIMENTO", "COMPETENCIA", "VALORORIGINAL", "VALORATUALIZADO"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1000, 470);

        jbpreencher.setBackground(new java.awt.Color(255, 255, 51));
        jbpreencher.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jbpreencher.setForeground(new java.awt.Color(255, 51, 51));
        jbpreencher.setText("PROCESSAR");
        jbpreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpreencherActionPerformed(evt);
            }
        });
        getContentPane().add(jbpreencher);
        jbpreencher.setBounds(740, 90, 130, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("CAMINHO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 20, 90, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("MATRICULA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 20, 100, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("ASSUNTOTIPO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 20, 110, 21);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 90, 110, 30);

        jttitulo1.setBackground(new java.awt.Color(102, 255, 204));
        jttitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttitulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jttitulo1);
        jttitulo1.setBounds(20, 50, 120, 30);

        jttitulo2.setBackground(new java.awt.Color(102, 255, 204));
        jttitulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttitulo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jttitulo2);
        jttitulo2.setBounds(160, 50, 120, 30);

        jttitulo3.setBackground(new java.awt.Color(102, 255, 204));
        jttitulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttitulo3ActionPerformed(evt);
            }
        });
        getContentPane().add(jttitulo3);
        jttitulo3.setBounds(300, 50, 120, 30);

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("LIMPAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(890, 50, 130, 40);
        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1049, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
        //// inicio do codigo
        JFileChooser fc = new JFileChooser();
         fc.setPreferredSize( new Dimension(750, 400) );
         
         fc.setFileSelectionMode(JFileChooser.FILES_ONLY );
        
         int resultado = fc.showOpenDialog(this);
                
                

                if ( resultado == JFileChooser.CANCEL_OPTION ) {
                    //para cancelar a janela se necessário
                }
                else{
                 file = fc.getSelectedFile();                
                            
                 jtlocal.setText(file.toString().trim());
                               
                    
                }
///////////// fim do codigo
                
                

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbpreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpreencherActionPerformed

               
  
    try {
        //////inicio do codigo
  
        workbook = Workbook.getWorkbook(new File(jtlocal.getText().trim()));
        
        
    } catch (IOException | BiffException ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
                 

                Sheet sheet = workbook.getSheet(0);
                             
                Cell c0 = sheet.getCell(0, 0);
                String titulo = c0.getContents();               
                
               
               jttitulo.setText(titulo);  
               
               
               int linhas = sheet.getRows();
           
               ////inicio do for
            for(int i = 3; i < linhas; i++){

                    Cell ca = sheet.getCell(0, i);
                    Cell cb = sheet.getCell(1, i);
                    Cell cc = sheet.getCell(2, i);
                    
                   
                    
                    String matricula = jttitulo1.getText();
                    String assuntotipo = jttitulo2.getText();
                    String datarequerimento = jttitulo3.getText();
                    
                    String competencia = ca.getContents();
                    String valororiginal = cb.getContents();
                    String valoratualizado = cc.getContents();
               
                        DefaultTableModel mp = (DefaultTableModel) tb1.getModel();                        
                        mp.addRow(new String[]{matricula,assuntotipo, datarequerimento, competencia,valororiginal,valoratualizado});

                    

             }   //////// fim do for

                workbook.close();
             
              
//////fim do codigo



    }//GEN-LAST:event_jbpreencherActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Escolhendo o caminho do arquivo usando um seletor de arquivos
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Salvar arquivo XML");
    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        exportToXML(fileToSave.getAbsolutePath());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttituloActionPerformed

    private void jttitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttitulo1ActionPerformed

    private void jttitulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttitulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttitulo2ActionPerformed

    private void jttitulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttitulo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttitulo3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              ((DefaultTableModel) tb1.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new Principal().setVisible(true);
    }
    });
}

/*public void SalvaArquivoXML (DefaultTableModel dtm){
	//XStream arquivoXML = new XStream();
	for (int j=0; j<=dtm.getRowCount(); j++)
	for(int i=0; i<=dtm.getColumnCount(); i++)
	{
		
		JOptionPane.showMessageDialog(null, (String)dtm.getValueAt(j,i));
	}
	
	
	
}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbpreencher;
    private javax.swing.JTextField jtlocal;
    private javax.swing.JTextField jttitulo;
    private javax.swing.JTextField jttitulo1;
    private javax.swing.JTextField jttitulo2;
    private javax.swing.JTextField jttitulo3;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

    private String Diretorio() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void CrearXml(tb1 JTable, String pruebaparaYouTube) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     *
     * @param absolutePath
     */
    private void exportToXML(String absolutePath) {
        
}
    private static class tb1 {

        public tb1() {
        }

        private int getRowCount() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
